[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]

remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@openzeppelin-06/=node_modules/@openzeppelin-06/"
]

eth_rpc_url = "https://rpc.ankr.com/eth_sepolia/953f006dec4231b66970373c2ce3b7b99d9e152e913b09f6365ba1ea00cb2685"
etherscan_api_key = '${ETHERSCAN_KEY}'
